version: '3.7'
services:
  xi2:
    privileged: true
    container_name: xi2
    image: xi2
    build:
     context: .
     dockerfile: Dockerfile
    shm_size: '2gb'
    volumes:
     - /storage-02/ml-mlang/repositories/:/workspace/repositories
     - /storage-02/ml-mlang/data/:/workspace/data
    entrypoint: [ "/bin/bash", "-l", "-c" ]
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
