#python unsup_prototype_nongroup/train.py -s 0
#python unsup_prototype_nongroup/train.py -s 1
python unsup_prototype_nongroup/train.py -s 2
python unsup_prototype_nongroup/train.py -s 3
python unsup_prototype_nongroup/train.py -s 4
python unsup_prototype_nongroup/train.py -s 5
python unsup_prototype_nongroup/train.py -s 6
python unsup_prototype_nongroup/train.py -s 7
python unsup_prototype_nongroup/train.py -s 8
python unsup_prototype_nongroup/train.py -s 9
